create extension if not exists vector;

create table if not exists public.documents (
    id integer generated by default as identity primary key,
    title varchar(500) not null,
    source_url text not null,
    agency varchar(100) not null,
    regulation_id varchar(100) not null,
    jurisdiction varchar(20) not null,
    state varchar(50),
    county varchar(100),
    industry_sectors text[] not null,
    min_employee_size integer,
    max_employee_size integer,
    effective_date date,
    full_text text not null,
    extra_metadata jsonb not null default '{}'::jsonb,
    required_document_types text[] not null,
    required_workflows text[] not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_documents_jurisdiction
    on public.documents (jurisdiction);

create index if not exists ix_documents_state
    on public.documents (state);

create index if not exists ix_documents_county
    on public.documents (county);

create index if not exists ix_documents_industry_sectors_gin
    on public.documents using gin (industry_sectors);

create index if not exists ix_documents_required_document_types_gin
    on public.documents using gin (required_document_types);

create index if not exists ix_documents_required_workflows_gin
    on public.documents using gin (required_workflows);

create table if not exists public.document_chunks (
    id integer generated by default as identity primary key,
    document_id integer not null references public.documents(id) on delete cascade,
    chunk_index integer not null,
    chunk_text text not null,
    embedding vector(1536) not null,
    token_count integer not null,
    created_at timestamptz not null default now(),
    constraint uq_document_chunk_position unique (document_id, chunk_index)
);

create index if not exists ix_document_chunks_document_id
    on public.document_chunks (document_id);

create index if not exists ix_document_chunks_embedding_hnsw
    on public.document_chunks using hnsw (embedding vector_cosine_ops);
