create extension if not exists vector;

drop table if exists public.document_chunks cascade;
drop table if exists public.documents cascade;
drop table if exists public.migration_test_dummy cascade;

create table if not exists public.regulations (
    id integer generated by default as identity primary key,
    industry varchar(100) not null,
    function varchar(100) not null,
    state varchar(100) not null,
    county varchar(150) not null,
    city_jurisdiction varchar(150) not null,
    level varchar(50) not null,
    jurisdiction_scope varchar(50) not null,
    applies_to_all_states boolean not null default false,
    applies_to_all_counties boolean not null default false,
    applies_to_all_cities boolean not null default false,
    regulation_name varchar(500) not null,
    regulation_code_reference varchar(255) not null,
    description text not null,
    action_required text not null,
    external_metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_regulations_canonical_identity unique (
        industry,
        function,
        state,
        county,
        city_jurisdiction,
        level,
        regulation_code_reference
    )
);

create index if not exists ix_regulations_level
    on public.regulations (level);

create index if not exists ix_regulations_state
    on public.regulations (state);

create index if not exists ix_regulations_county
    on public.regulations (county);

create index if not exists ix_regulations_city_jurisdiction
    on public.regulations (city_jurisdiction);

create index if not exists ix_regulations_industry
    on public.regulations (industry);

create index if not exists ix_regulations_function
    on public.regulations (function);

create index if not exists ix_regulations_regulation_name
    on public.regulations (regulation_name);

create index if not exists ix_regulations_regulation_code_reference
    on public.regulations (regulation_code_reference);

create table if not exists public.regulation_vectors (
    id integer generated by default as identity primary key,
    regulation_id integer not null unique references public.regulations(id) on delete cascade,
    search_text text not null,
    embedding vector(1536) not null,
    token_count integer not null,
    created_at timestamptz not null default now()
);

create index if not exists ix_regulation_vectors_regulation_id
    on public.regulation_vectors (regulation_id);

create index if not exists ix_regulation_vectors_embedding_hnsw
    on public.regulation_vectors using hnsw (embedding vector_cosine_ops);

create table if not exists public.source_documents (
    id integer generated by default as identity primary key,
    title varchar(500) not null,
    source_url text unique,
    source_type varchar(100) not null,
    publisher_agency varchar(255),
    publication_date date,
    effective_date date,
    checksum varchar(128) unique,
    external_identifier varchar(255),
    mime_type varchar(100),
    raw_text text,
    storage_reference text,
    ingestion_status varchar(50) not null default 'pending',
    external_metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists ix_source_documents_source_type
    on public.source_documents (source_type);

create index if not exists ix_source_documents_publisher_agency
    on public.source_documents (publisher_agency);

create table if not exists public.source_document_chunks (
    id integer generated by default as identity primary key,
    source_document_id integer not null references public.source_documents(id) on delete cascade,
    chunk_index integer not null,
    chunk_text text not null,
    embedding vector(1536) not null,
    token_count integer not null,
    created_at timestamptz not null default now(),
    constraint uq_source_document_chunk_position unique (source_document_id, chunk_index)
);

create index if not exists ix_source_document_chunks_source_document_id
    on public.source_document_chunks (source_document_id);

create index if not exists ix_source_document_chunks_embedding_hnsw
    on public.source_document_chunks using hnsw (embedding vector_cosine_ops);

create table if not exists public.regulation_document_links (
    id integer generated by default as identity primary key,
    regulation_id integer not null references public.regulations(id) on delete cascade,
    source_document_id integer not null references public.source_documents(id) on delete cascade,
    relationship_type varchar(100) not null default 'supports',
    confidence double precision,
    citation_note text,
    created_at timestamptz not null default now(),
    constraint uq_regulation_document_link unique (regulation_id, source_document_id, relationship_type)
);

create index if not exists ix_regulation_document_links_regulation_id
    on public.regulation_document_links (regulation_id);

create index if not exists ix_regulation_document_links_source_document_id
    on public.regulation_document_links (source_document_id);
