-- Simple dummy table to verify `supabase db push` / migrations against a remote project.
-- Drop when no longer needed: drop table if exists public.migration_test_dummy;

create table if not exists public.migration_test_dummy (
    id bigint generated by default as identity primary key,
    label text not null default 'dummy',
    created_at timestamptz not null default now()
);

create index if not exists ix_migration_test_dummy_created_at
    on public.migration_test_dummy (created_at desc);
